# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ab345a919c06dd254c6792f7c03a056340257a1d3b78d2023be0611574647faaf714041625a7b5c1c24282612adfb3f3d37d6891cb333894c08dba7e154fe5d

test:
  secret_key_base: ec0c9e3d095a5565bf73e42ea76ed2ee76427724f2a82dc6bfbfd60e5feeeea3fd56b9a852e5af32a30de37197ba50c9f6d98e1f2d2e24bf674d2db8f6a22921

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
